export const errorMessage = {
  INVALID_DATA: 'Provided data is invalid',
  OTP_EXPIRED: 'OTP expired, please try again',
  ACCOUNT_EXISTS: 'Account already exists',
  ACCOUNT_NOT_EXISTS: 'Account not exists',
  BLOCKED: 'Account is blocked. Please contact Admin',
  REJECTED: 'Account verification failed. Please signup again',
  UNVERIFIED: 'Account under verification. Try after sometime',
  UNAUTHORIZED: 'Not authenticated. Please signin',
  SESSION_EXPIRED: 'Session expired. Please try again',
  FORBIDDEN: 'Access denied due to insufficient permission',
  WRONG_PASSWORD: 'Wrong password',
  SOMETHING_WRONG: 'Something went wrong',
  VIDEO: 'Video must be 30 seconds or less',
  STATUS_NOT_UPDATED: 'Status not updated',
  VERIFICATION_FAILED: 'Verification failed',
  REVIEW_NOT_FOUND: 'Review not found',
  REVIEW_SESSION_REQUIRED: 'You must complete at least one session with this tutor to leave a review',
  REVIEW_ALREADY_EXISTS: 'You have already reviewed this tutor',
  REVIEW_NOT_AUTHORIZED: 'You are not authorized to perform this action on this review',
  TUTOR_ID_REQUIRED: 'Tutor ID is required',
  RATING_MIN: 'Rating must be at least 1',
  RATING_MAX: 'Rating cannot exceed 5',
  NOTE_MIN: 'Review note must be at least 5 characters long',
  NOTE_MAX: 'Review note cannot exceed 500 characters',
  RECEIVER_ID_REQUIRED: 'Receiver ID is required',
  MESSAGE_TEXT_REQUIRED: 'Message text is required',
  MESSAGE_TEXT_MAX: 'Message text cannot exceed 1000 characters',
};
