export const successMessage = {
  SIGNUP_SUCCESS: 'Signup successful',
  ACCOUNT_RESUBMITTED: 'Account resubmission successful',
  SIGNIN_SUCCESS: 'Signin successful',
  SIGNOUT_SUCCESS: 'Signout successful',
  OTP_SENDED: 'OTP sended',
  OTP_VERIFIED: 'OTP verified',
  PASSWORD_UPDATED: 'Password successfully updated',
  DATA_FETCH_SUCCESS: 'Data fetched successfully',
  NOTIFICATION_MARKED_READ: 'Notification marked as read',
  ALL_NOTIFICATIONS_MARKED_READ: 'All notifications marked as read',
  AVATAR_UPLOADED: 'Avatar successfully uploaded',
  AVATAR_DELETED: 'Avatar successfully deleted',
  STATUS_UPDATED: 'Status successfully updated',
  VERIFIED: 'Successfully verified',
  PROFILE_UPDATED: 'Profile successfully updated',
  ORDER_CREATED: 'Order created successfully',
  BOOKING_SUCCESS: 'Booking successful',
  REVIEW_ADDED: 'Review added successfully',
  REVIEW_UPDATED: 'Review updated successfully',
  REVIEW_DELETED: 'Review deleted successfully',
};
