export const API_ROUTES = {
  USER: {
    SIGNUP: '/user/signup',
    FINISH_SIGNUP: '/user/finish-signup',
    VERIFY_OTP: '/user/verify-otp',
    VERIFY_EMAIL: '/user/verify-email',
    RESEND_OTP: '/user/resend-otp',
    FORGOT_PASSWORD_OTP_VERIFY: '/user/forgot-password-otp-verify',
    RESET_PASSWORD: '/user/reset-password',
    SIGNIN: '/user/signin',
    GOOGLE_SIGNIN: '/user/auth/google',
    GET_ACCOUNT_DETAILS: '/user/get-account-details',
    FETCH_AVATAR: `${process.env.NEXT_PUBLIC_S3_OBJECT_URL}/users/avatars`,
    UPLOAD_AVATAR: '/user/upload-avatar',
    DELETE_AVATAR: '/user/delete-avatar',
    UPDATE_PROFILE: '/user/update-profile',
    CHANGE_PASSWORD: '/user/change-password',
    SIGNOUT: '/user/signout',
    GET_TUTORS: '/user/tutors',
    CREATE_ORDER: '/user/book/order',
    VERIFY_PAYMENT: '/user/book/verify',
    REVIEWS: '/user/reviews',
    TUTOR_REVIEWS: (tutorId: string) => `/user/tutors/${tutorId}/reviews`,
    REVIEW_ELIGIBILITY: (tutorId: string) => `/user/tutors/${tutorId}/review-eligibility`,
    CHATS: '/user/chats',
    CHAT_MESSAGES: (id: string) => `/user/chats/${id}/messages`,
    SEND_MESSAGE: '/user/chats/messages',
    CHAT_SEARCH: '/user/chats/search',
    NOTIFICATIONS: '/user/notifications',
    MARK_READ: (id: string) => `/user/notifications/${id}/read`,
    MARK_ALL_READ: '/user/notifications/read-all',
    UNREAD_COUNT: '/user/notifications/unread-count',
    REPORTS: '/user/reports',
  },
  TUTOR: {
    SIGNUP: '/tutor/signup',
    FINISH_SIGNUP: '/tutor/finish-signup',
    RESUBMIT_ACCOUNT: '/tutor/resubmit-account',
    VERIFY_OTP: '/tutor/verify-otp',
    VERIFY_EMAIL: '/tutor/verify-email',
    RESEND_OTP: '/tutor/resend-otp',
    FORGOT_PASSWORD_OTP_VERIFY: '/tutor/forgot-password-otp-verify',
    RESET_PASSWORD: '/tutor/reset-password',
    SIGNIN: '/tutor/signin',
    GOOGLE_SIGNIN: '/tutor/auth/google',
    GET_ACCOUNT_DETAILS: '/tutor/get-account-details',
    FETCH_AVATAR: `${process.env.NEXT_PUBLIC_S3_OBJECT_URL}/tutors/avatars`,
    FETCH_VIDEO: `${process.env.NEXT_PUBLIC_S3_OBJECT_URL}/tutors/videos`,
    FETCH_CERTIFICATE: `${process.env.NEXT_PUBLIC_S3_OBJECT_URL}/tutors/certificates`,
    UPLOAD_AVATAR: '/tutor/upload-avatar',
    DELETE_AVATAR: '/tutor/delete-avatar',
    UPDATE_PROFILE: '/tutor/update-profile',
    CHANGE_PASSWORD: '/tutor/change-password',
    SIGNOUT: '/tutor/signout',
    CREATE_SESSION: '/tutor/create-session',
    GET_SESSIONS: '/tutor/get-sessions',
    CANCEL_SESSION: '/tutor/cancel-session',
    NOTIFICATIONS: '/tutor/notifications',
    MARK_READ: (id: string) => `/tutor/notifications/${id}/read`,
    MARK_ALL_READ: '/tutor/notifications/read-all',
    UNREAD_COUNT: '/tutor/notifications/unread-count',
    REPORTS: '/tutor/reports',
  },
  ADMIN: {
    SIGNIN: '/admin/signin',
    GET_ACCOUNT_DETAILS: '/admin/get-account-details',
    SIGNOUT: '/admin/signout',
    USERS: '/admin/users',
    TUTORS: '/admin/tutors',
    REPORTS: '/admin/reports',
    HANDLE_REPORT: (id: string) => `/admin/reports/${id}`,
  },
};
