export const API_ROUTES = {
  USER: {
    SIGNUP: '/user/signup',
    VERIFY_OTP: '/user/verify-otp',
    VERIFY_EMAIL: '/user/verify-email',
    RESEND_OTP: '/user/resend-otp',
    FORGOT_PASSWORD_OTP_VERIFY: '/user/forgot-password-otp-verify',
    RESET_PASSWORD: '/user/reset-password',
    SIGNIN: '/user/signin',
    GOOGLE_SIGNIN: '/user/auth/google',
    GET_ACCOUNT_DETAILS: '/user/get-account-details',
    FETCH_AVATAR: `${process.env.NEXT_PUBLIC_S3_OBJECT_URL}/users/avatars`,
    UPLOAD_AVATAR: '/user/upload-avatar',
    DELETE_AVATAR: '/user/delete-avatar',
    UPDATE_PROFILE: '/user/update-profile',
    CHANGE_PASSWORD: '/user/change-password',
  },
  TUTOR: {
    SIGNUP: '/tutor/signup',
    VERIFY_OTP: '/tutor/verify-otp',
    VERIFY_EMAIL: '/tutor/verify-email',
    RESEND_OTP: '/tutor/resend-otp',
    FORGOT_PASSWORD_OTP_VERIFY: '/tutor/forgot-password-otp-verify',
    RESET_PASSWORD: '/tutor/reset-password',
    SIGNIN: '/tutor/signin',
    GOOGLE_SIGNIN: '/tutor/auth/google',
    GET_ACCOUNT_DETAILS: '/tutor/get-account-details',
    FETCH_AVATAR: `${process.env.NEXT_PUBLIC_S3_OBJECT_URL}/users/avatars`,
    UPLOAD_AVATAR: '/tutor/upload-avatar',
    DELETE_AVATAR: '/tutor/delete-avatar',
    UPDATE_PROFILE: '/tutor/update-profile',
    CHANGE_PASSWORD: '/tutor/change-password',
  },
};
